prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/shared_components/navigation/lists/access_control.sql
@@application/shared_components/navigation/lists/dashboard.sql
@@application/shared_components/navigation/lists/kvs_context_menu.sql
@@application/shared_components/navigation/lists/kvs_administration.sql
@@application/shared_components/navigation/lists/dba_utilities.sql
@@application/shared_components/navigation/lists/kvs_navigation_bar.sql
@@application/shared_components/navigation/lists/kvs_side_menu.sql
@@application/shared_components/files/js_common_min_js.sql
@@application/shared_components/files/js_31005_js.sql
@@application/shared_components/files/js_apex41018_js.sql
@@application/shared_components/files/js_apex41028_js.sql
@@application/shared_components/files/js_apex41033_js.sql
@@application/shared_components/files/css_global_css.sql
@@application/shared_components/files/js_41026_js.sql
@@application/shared_components/files/js_31006_js.sql
@@application/shared_components/files/js_41006_js.sql
@@application/shared_components/files/js_41031_js.sql
@@application/shared_components/files/js_81006_js.sql
@@application/shared_components/files/js_81010_js.sql
@@application/shared_components/files/js_31016_js.sql
@@application/shared_components/files/js_3120_js.sql
@@application/shared_components/files/js_83005_js.sql
@@application/shared_components/files/js_col1160_js.sql
@@application/shared_components/files/js_col1210_js.sql
@@application/shared_components/files/js_col2010_js.sql
@@application/shared_components/files/js_col2020_js.sql
@@application/shared_components/files/js_col3030_js.sql
@@application/shared_components/files/js_col3040_js.sql
@@application/shared_components/files/js_col3110_js.sql
@@application/shared_components/files/js_col3160_js.sql
@@application/shared_components/files/js_kvs_qb_js.sql
@@application/shared_components/files/js_kvs1030_js.sql
@@application/shared_components/files/kcicon_png.sql
@@application/shared_components/files/kcicon2_png.sql
@@application/shared_components/files/js_common_js.sql
@@application/shared_components/files/js_rememberpageig_js.sql
@@application/shared_components/files/css_baseline_css.sql
@@application/shared_components/files/js_budadjlib_js.sql
@@application/shared_components/files/js_baselinelib_js.sql
@@application/plugin_settings.sql
@@application/shared_components/security/app_access_control/administrator.sql
@@application/shared_components/security/app_access_control/contributor.sql
@@application/shared_components/security/app_access_control/reader.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/selectqe.sql
@@application/shared_components/logic/application_processes/getimage.sql
@@application/shared_components/logic/application_processes/get_popup_item_list.sql
@@application/shared_components/logic/application_processes/validate_contextmenu.sql
@@application/shared_components/logic/application_processes/get_page_url.sql
@@application/shared_components/logic/application_processes/get_kvsdoc_url.sql
@@application/shared_components/logic/application_processes/get_property_url.sql
@@application/shared_components/logic/application_processes/get_page_url_dtl.sql
@@application/shared_components/logic/application_items/g_dload_seq.sql
@@application/shared_components/logic/application_items/g_home.sql
@@application/shared_components/logic/application_items/g_home_icon.sql
@@application/shared_components/logic/application_items/g_jobcount.sql
@@application/shared_components/logic/application_items/p_fiscal_period_from.sql
@@application/shared_components/logic/application_items/p_fiscal_period_to.sql
@@application/shared_components/logic/application_items/p_period_1.sql
@@application/shared_components/logic/application_items/p_period_2.sql
@@application/shared_components/logic/application_items/p_period_3.sql
@@application/shared_components/logic/application_items/p_request.sql
@@application/shared_components/logic/application_items/p_return_41006.sql
@@application/shared_components/logic/application_computations/g_home_icon.sql
@@application/shared_components/logic/application_computations/p0_user.sql
@@application/shared_components/logic/application_computations/g_jobcount.sql
@@application/shared_components/logic/application_computations/p0_sid.sql
@@application/shared_components/logic/application_computations/p_request.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/access_roles.sql
@@application/shared_components/user_interface/lovs/apex_application_mode.sql
@@application/shared_components/user_interface/lovs/apex_application_priv.sql
@@application/shared_components/user_interface/lovs/col_adjs.sql
@@application/shared_components/user_interface/lovs/col_adj_ledgers.sql
@@application/shared_components/user_interface/lovs/col_bill_types.sql
@@application/shared_components/user_interface/lovs/col_districts.sql
@@application/shared_components/user_interface/lovs/col_due_date_tables.sql
@@application/shared_components/user_interface/lovs/col_exemptions.sql
@@application/shared_components/user_interface/lovs/col_exts.sql
@@application/shared_components/user_interface/lovs/col_lockbox_formats.sql
@@application/shared_components/user_interface/lovs/col_memo_types.sql
@@application/shared_components/user_interface/lovs/col_nbhds.sql
@@application/shared_components/user_interface/lovs/col_notices.sql
@@application/shared_components/user_interface/lovs/col_parcel_tables.sql
@@application/shared_components/user_interface/lovs/col_prop_classes.sql
@@application/shared_components/user_interface/lovs/col_purposes.sql
@@application/shared_components/user_interface/lovs/col_purpose_tables.sql
@@application/shared_components/user_interface/lovs/col_rate_groups.sql
@@application/shared_components/user_interface/lovs/col_reasons.sql
@@application/shared_components/user_interface/lovs/col_retunpd_formats.sql
@@application/shared_components/user_interface/lovs/col_roll_sections.sql
@@application/shared_components/user_interface/lovs/col_schools.sql
@@application/shared_components/user_interface/lovs/col_seqs.sql
@@application/shared_components/user_interface/lovs/col_seq_access.sql
@@application/shared_components/user_interface/lovs/col_setup_bank_bills.sql
@@application/shared_components/user_interface/lovs/col_summ_codes.sql
@@application/shared_components/user_interface/lovs/col_taxing_basis.sql
@@application/shared_components/user_interface/lovs/col_user_defined.sql
@@application/shared_components/user_interface/lovs/col_veh_classes.sql
@@application/shared_components/user_interface/lovs/col_ys_years.sql
@@application/shared_components/user_interface/lovs/email_username_format.sql
@@application/shared_components/user_interface/lovs/fa_classes.sql
@@application/shared_components/user_interface/lovs/fa_clients.sql
@@application/shared_components/user_interface/lovs/gl_acct_types.sql
@@application/shared_components/user_interface/lovs/gl_alt_groups.sql
@@application/shared_components/user_interface/lovs/gl_budget_check.sql
@@application/shared_components/user_interface/lovs/gl_grants.sql
@@application/shared_components/user_interface/lovs/gl_muni_segments.sql
@@application/shared_components/user_interface/lovs/gl_open_period.sql
@@application/shared_components/user_interface/lovs/gl_years.sql
@@application/shared_components/user_interface/lovs/gr_customers.sql
@@application/shared_components/user_interface/lovs/gr_payment_types.sql
@@application/shared_components/user_interface/lovs/gr_printer_formats.sql
@@application/shared_components/user_interface/lovs/gr_roll_types.sql
@@application/shared_components/user_interface/lovs/kvs_id_types.sql
@@application/shared_components/user_interface/lovs/kvs_adv_abs.sql
@@application/shared_components/user_interface/lovs/kvs_banks.sql
@@application/shared_components/user_interface/lovs/kvs_column_delimiters.sql
@@application/shared_components/user_interface/lovs/kvs_currencies.sql
@@application/shared_components/user_interface/lovs/kvs_data_types.sql
@@application/shared_components/user_interface/lovs/kvs_file_formats.sql
@@application/shared_components/user_interface/lovs/kvs_font_name.sql
@@application/shared_components/user_interface/lovs/kvs_group_securities.sql
@@application/shared_components/user_interface/lovs/kvs_modules.sql
@@application/shared_components/user_interface/lovs/kvs_module_types.sql
@@application/shared_components/user_interface/lovs/kvs_months.sql
@@application/shared_components/user_interface/lovs/kvs_munis.sql
@@application/shared_components/user_interface/lovs/kvs_ob.sql
@@application/shared_components/user_interface/lovs/kvs_printers.sql
@@application/shared_components/user_interface/lovs/kvs_printer_types.sql
@@application/shared_components/user_interface/lovs/kvs_print_multi_invoice.sql
@@application/shared_components/user_interface/lovs/kvs_required_tablles.sql
@@application/shared_components/user_interface/lovs/kvs_row_delimiters.sql
@@application/shared_components/user_interface/lovs/kvs_states.sql
@@application/shared_components/user_interface/lovs/kvs_status_ai.sql
@@application/shared_components/user_interface/lovs/kvs_status_bp.sql
@@application/shared_components/user_interface/lovs/kvs_systems.sql
@@application/shared_components/user_interface/lovs/kvs_users.sql
@@application/shared_components/user_interface/lovs/kvs_wf_groups.sql
@@application/shared_components/user_interface/lovs/kvs_workflows.sql
@@application/shared_components/user_interface/lovs/kvs_yes_no.sql
@@application/shared_components/user_interface/lovs/kvs_yes_no_long.sql
@@application/shared_components/user_interface/lovs/lov_gl1010l.sql
@@application/shared_components/user_interface/lovs/lov_gl1010p_deprecated.sql
@@application/shared_components/user_interface/lovs/lov_gl1010p_vyear.sql
@@application/shared_components/user_interface/lovs/lov_gl1010y.sql
@@application/shared_components/user_interface/lovs/lov_gl1010y2.sql
@@application/shared_components/user_interface/lovs/lov_gl1020l.sql
@@application/shared_components/user_interface/lovs/lov_gl1030l.sql
@@application/shared_components/user_interface/lovs/lov_gl1040l.sql
@@application/shared_components/user_interface/lovs/lov_gl1040l_desc.sql
@@application/shared_components/user_interface/lovs/lov_gl1051l.sql
@@application/shared_components/user_interface/lovs/lov_gl1052l.sql
@@application/shared_components/user_interface/lovs/lov_gl1070l.sql
@@application/shared_components/user_interface/lovs/lov_gl1071l.sql
@@application/shared_components/user_interface/lovs/lov_gl1080l.sql
@@application/shared_components/user_interface/lovs/lov_gl1100l.sql
@@application/shared_components/user_interface/lovs/lov_gl1110l.sql
@@application/shared_components/user_interface/lovs/lov_gl2010l.sql
@@application/shared_components/user_interface/lovs/lov_glr_bsort.sql
@@application/shared_components/user_interface/lovs/lov_kvs1020l_xpost.sql
@@application/shared_components/user_interface/lovs/lov_pur1020l.sql
@@application/shared_components/user_interface/lovs/lov_pur1030l.sql
@@application/shared_components/user_interface/lovs/lov_pur1040l.sql
@@application/shared_components/user_interface/lovs/lov_pur1050l.sql
@@application/shared_components/user_interface/lovs/lov_pur1060l.sql
@@application/shared_components/user_interface/lovs/lov_pur1060l_grid.sql
@@application/shared_components/user_interface/lovs/lov_pur1071l.sql
@@application/shared_components/user_interface/lovs/lov_pur1071l_vendore_code.sql
@@application/shared_components/user_interface/lovs/lov_pur1072l_deprecated.sql
@@application/shared_components/user_interface/lovs/lov_pur1073l.sql
@@application/shared_components/user_interface/lovs/lov_pur1080l.sql
@@application/shared_components/user_interface/lovs/lov_pur1080l_ap.sql
@@application/shared_components/user_interface/lovs/lov_pur1090l.sql
@@application/shared_components/user_interface/lovs/lov_pur1100l.sql
@@application/shared_components/user_interface/lovs/lov_pur1110l.sql
@@application/shared_components/user_interface/lovs/lov_pur1110l_status_a.sql
@@application/shared_components/user_interface/lovs/lov_pur1180l.sql
@@application/shared_components/user_interface/lovs/lov_pur1180l_ap.sql
@@application/shared_components/user_interface/lovs/lov_pur1200l.sql
@@application/shared_components/user_interface/lovs/lov_pur2020l.sql
@@application/shared_components/user_interface/lovs/lov_pur2030l.sql
@@application/shared_components/user_interface/lovs/lov_pur2040l.sql
@@application/shared_components/user_interface/lovs/lov_report_muni.sql
@@application/shared_components/user_interface/lovs/pr_benefits.sql
@@application/shared_components/user_interface/lovs/pr_deductions.sql
@@application/shared_components/user_interface/lovs/pr_status.sql
@@application/shared_components/user_interface/lovs/pur_ap_bank_accts.sql
@@application/shared_components/user_interface/lovs/pur_bill_tos.sql
@@application/shared_components/user_interface/lovs/pur_print_order_approved_by.sql
@@application/shared_components/user_interface/lovs/pur_ship_tos.sql
@@application/shared_components/user_interface/lovs/pur_state_list.sql
@@application/shared_components/user_interface/lovs/pur_vendors.sql
@@application/shared_components/user_interface/lovs/pur_vendor_addrs_vendor.sql
@@application/shared_components/user_interface/lovs/pur_vendor_addrs_vendor2.sql
@@application/shared_components/user_interface/lovs/pur_vendor_types.sql
@@application/shared_components/user_interface/lovs/tb_tax_rolls.sql
@@application/shared_components/user_interface/lovs/test_lov_dynamic.sql
@@application/shared_components/user_interface/lovs/ub_acct_types.sql
@@application/shared_components/user_interface/lovs/ub_export_format_sort.sql
@@application/shared_components/user_interface/lovs/ub_import_dtl_type.sql
@@application/shared_components/user_interface/lovs/ub_meter_placement.sql
@@application/shared_components/user_interface/lovs/ub_rates.sql
@@application/shared_components/user_interface/lovs/ub_reading_types.sql
@@application/shared_components/user_interface/lovs/ub_read_codes.sql
@@application/shared_components/user_interface/lovs/ub_service_codes.sql
@@application/shared_components/user_interface/lovs/ub_service_groups.sql
@@application/shared_components/user_interface/lovs/ub_service_types.sql
@@application/shared_components/user_interface/lovs/ub_statuses.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/kvs_breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/page/drawer.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/button/html_button_legacy_apex_5_migration.sql
@@application/shared_components/user_interface/templates/region/image.sql
@@application/shared_components/user_interface/templates/region/inline_drawer.sql
@@application/shared_components/user_interface/templates/region/cards_container.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/list/kvs_side_navigation_menu.sql
@@application/shared_components/user_interface/templates/report/contextual_info.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/user_interface/shortcuts/delete_confirm_msg.sql
@@application/shared_components/security/authentications/apex.sql
@@application/shared_components/security/authentications/kvs.sql
@@application/shared_components/plugins/process_type/be_apexrnd_aop.sql
@@application/shared_components/plugins/item_type/com_oracle_apex_simple_checkbox.sql
@@application/shared_components/plugins/dynamic_action/be_apexrnd_aop_da.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_timelinestatuslist.sql
@@application/shared_components/plugins/dynamic_action/be_apexrnd_aop_convert_da.sql
@@application/user_interfaces.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00004.sql
@@application/pages/page_00012.sql
@@application/pages/page_00020.sql
@@application/pages/page_00101.sql
@@application/pages/page_01020.sql
@@application/pages/page_01021.sql
@@application/pages/page_01025.sql
@@application/pages/page_01026.sql
@@application/pages/page_01040.sql
@@application/pages/page_02000.sql
@@application/pages/page_02005.sql
@@application/pages/page_02010.sql
@@application/pages/page_02015.sql
@@application/pages/page_02025.sql
@@application/pages/page_02026.sql
@@application/pages/page_02035.sql
@@application/pages/page_02040.sql
@@application/pages/page_02050.sql
@@application/pages/page_02060.sql
@@application/pages/page_03120.sql
@@application/pages/page_03121.sql
@@application/pages/page_03122.sql
@@application/pages/page_30000.sql
@@application/pages/page_31005.sql
@@application/pages/page_31006.sql
@@application/pages/page_31007.sql
@@application/pages/page_31008.sql
@@application/pages/page_31009.sql
@@application/pages/page_31028.sql
@@application/pages/page_34012.sql
@@application/pages/page_34017.sql
@@application/pages/page_34022.sql
@@application/pages/page_41006.sql
@@application/pages/page_41007.sql
@@application/pages/page_81003.sql
@@application/pages/page_81004.sql
@@application/pages/page_81005.sql
@@application/pages/page_81006.sql
@@application/pages/page_81007.sql
@@application/pages/page_81008.sql
@@application/pages/page_81009.sql
@@application/pages/page_82015.sql
@@application/pages/page_83010.sql
@@application/pages/page_83020.sql
@@application/pages/page_83021.sql
@@application/pages/page_83022.sql
@@application/deployment/definition.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
